from app import db, Units, CaseUnitMapper, CaseTestResults, CaseNotes, CaseHistory, NormalTestResults

def add(obj):
    db.session.add(obj)
    db.session.commit()

db.create_all()

#  Create Units Table
osmo = Units(unit = "Osmolality and Electrolytes")
renal = Units(unit = "Renal Physiology")
lipids = Units(unit = "Apolipoprotein Metabolism")
hepatitis_hiv = Units(unit = "Viral Hepatitis and HIV")
enzymes = Units(unit = "Enzymology")

add(osmo)
add(renal)
add(lipids)
add(hepatitis_hiv)
add(enzymes)

#  Case 1 -SIADH
case_1 = CaseUnitMapper(caseID = 1, unitID = 1, unit = osmo)
add(case_1)

case_1_sodium = CaseTestResults(testName = "Sodium", lowerBound = 110, upperBound = 125, units = "mEq/L", valueType = 'integer', case = case_1)
case_1_osmolality = CaseTestResults(testName = "Osmolality", lowerBound = 245, upperBound = 265, units = "mOsm/kg", valueType = 'integer', case = case_1)
case_1_urine_osmo = CaseTestResults(testName = "Urine_Osmolality", lowerBound = 315, upperBound = 335, units = "mOsm/kg", valueType = 'integer', case = case_1)
case_1_urine_sodium = CaseTestResults(testName = "Urine_Sodium", lowerBound = 80, upperBound = 120, units = "mEq/L", valueType = 'integer', case = case_1)
case_1_glucose = CaseTestResults(testName = "Glucose", lowerBound = 120, upperBound = 160, units = "mg/dL", valueType = 'integer', case = case_1)
case_1_co2 = CaseTestResults(testName = "CO2", lowerBound = 20, upperBound = 24, units = "mEq/L", valueType = 'float', precision = 1, case = case_1)
case_1_chloride = CaseTestResults(testName = "Chloride", lowerBound = 90, upperBound = 95, units = "mEq/L", valueType = 'integer', case = case_1)
add(case_1_sodium)
add(case_1_osmolality)
add(case_1_urine_osmo)
add(case_1_urine_sodium)
add(case_1_glucose)
add(case_1_co2)
add(case_1_chloride)

case_1_note_1 = CaseNotes(note = "ED - April 11 2019\n 28 year old female presents to the ER complaining of progressively worsening headaches for 5 days. Patient has noticably slurred speech and difficulty walking. Denies tobacco and alcohol use. Denies illicit drug use. Eating and exercise habits are normal. Denies any missed insulin doses. No other medications besides insulin.", noteType = "history", location = "ED", date = "Thurs April 11 2019 11:15:17", case = case_1)
case_1_note_2 = CaseNotes(note = "ED - April 11 2019\n Temperature: 37.1C, BP: 114 / 72, HR: 83, POC glucose: 105", noteType = "vitals", location = "ED", date = "April 11 2019 11:18:25", case = case_1)
case_1_note_3 = CaseNotes(note = "ED - April 11 2019\n Physical exam: normal findings. No masses or lesions, no organomegaly. No peripheral edema.\nNeurologic exam: impaired physical coordination - abnormal gait. No obvious signs of trauma, no pain with movement. Slurred speech with no signs of stroke or CNS injury.", noteType = "exam", location = "ED", date = "April 11 2019, 11:49:01", case = case_1)
add(case_1_note_1)
add(case_1_note_2)
add(case_1_note_3)

case_1_history_1 = CaseHistory(diagnosis = "Small cell lung cancer", date = "Thurs April 23 2015, 12:06:19", reference = "https://my.clevelandclinic.org/health/articles/6202-small-cell-lung-cancer", reference_name = "Cleveland Clinic - SCL", case = case_1)
case_1_history_2 = CaseHistory(diagnosis = "Diabetes Mellitus, Type II", date = "Sat July 07 2012, 17:21:48", reference = "https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/symptoms-causes/syc-20351193", reference_name = "Mayo Clinic - DM II", case = case_1)
case_1_history_3 = CaseHistory(diagnosis = "Cholecystectomy due to cholelithiasis", date = "Fri November 06 2009, 09:22:00", reference = "https://www.hopkinsmedicine.org/health/treatment-tests-and-therapies/cholecystectomy", reference_name = "Johns Hopkins - Cholecystectomy", case = case_1)
add(case_1_history_1)
add(case_1_history_2)
add(case_1_history_3)


#  Normal Test Results
normal_sodium = NormalTestResults(testName = "Sodium", lowerBound = 138, upperBound = 148, units = "mEq/L", valueType = "integer")
normal_potassium = NormalTestResults(testName = "Potassium", lowerBound = 3.5, upperBound = 5.3, units = "mEq/L", valueType = "float", precision = 1)
normal_chloride = NormalTestResults(testName = "Chloride", lowerBound = 92, upperBound = 103, units = "mEq/L", valueType = "integer")
normal_co2 = NormalTestResults(testName = "CO2", lowerBound = 22, upperBound = 27, units = "mEq/L", valueType = "float", precision = 1)
normal_mg = NormalTestResults(testName = "Magnesium", lowerBound = 1.6, upperBound = 2.6, units = "mEq/L", valueType = "float", precision = 1)
normal_phosphorus = NormalTestResults(testName = "Phosphorus", lowerBound = 2.5, upperBound = 4.5, units = "mEq/L", valueType = "float", precision = 1)
normal_calcium = NormalTestResults(testName = "Calcium", lowerBound = 8.6, upperBound = 10.0, units = "mEq/L", valueType = "float", precision = 1)
normal_glucose = NormalTestResults(testName = "Glucose", lowerBound = 70, upperBound = 100, units = "mg/dL", valueType = "integer")
normal_creatinine = NormalTestResults(testName = "Creatinine", lowerBound = 0.70, upperBound = 1.25, units = "mg/dL", valueType = "float", precision = 2)
normal_bun = NormalTestResults(testName = "BUN", lowerBound = 6, upperBound = 20, units = "mg/dL", valueType = "integer")
normal_albumin = NormalTestResults(testName = "Albumin", lowerBound = 3.4, upperBound = 5.0, units = "g/dL", valueType = "float", precision = 1)
normal_total_protein = NormalTestResults(testName = "Total_Protein", lowerBound = 6.4, upperBound = 8.3, units = "g/dL", valueType = "float", precision = 1)
normal_ast = NormalTestResults(testName = "AST", lowerBound = 5, upperBound = 40, units = "IU/L", valueType = "integer")
normal_alt = NormalTestResults(testName = "ALT", lowerBound = 0, upperBound = 41, units = "IU/L", valueType = "integer")
normal_alk_phos = NormalTestResults(testName = "Alkaline_Phosphatase", lowerBound = 40, upperBound = 129, units = "IU/L", valueType = "integer")
normal_direct_bilirubin = NormalTestResults(testName = "Direct_Bilirubin", lowerBound = 0.0, upperBound = 0.2, units = "mg/dL", valueType = "float", precision = 1)
normal_total_bilirubin = NormalTestResults(testName = "Total_Bilirubin", lowerBound = 0.0, upperBound = 1.2, units = "mg/dL", valueType = "float", precision = 1)
normal_iron = NormalTestResults(testName = "Iron", lowerBound = 59, upperBound = 128, units = "\u03BCg/dL", valueType = "integer")
normal_transferrin = NormalTestResults(testName = "Transferrin", lowerBound = 200, upperBound = 360, units = "mg/dL", valueType = "integer")
normal_ferritin = NormalTestResults(testName = "Ferritin", lowerBound = 30, upperBound = 400, units = "ng/mL", valueType = "integer")
normal_crp = NormalTestResults(testName = "CRP", lowerBound = 0.0, upperBound = 5.0, units = "mg/L", valueType = "float", precision = 1)
normal_triglycerides = NormalTestResults(testName = "Triglycerides", lowerBound = 10, upperBound = 150, units = "mg/dL", valueType = "integer")
normal_hdl = NormalTestResults(testName = "HDL", lowerBound = 40, upperBound = 75, units = "mg/dL", valueType = "integer")
normal_ldl = NormalTestResults(testName = "LDL", lowerBound = 80, upperBound = 200, units = "mg/dL", valueType = "integer")
normal_total_cholesterol = NormalTestResults(testName = "Total_Cholesterol", lowerBound = 0, upperBound = 250, units = "mg/dL", valueType = "integer")
normal_tsh = NormalTestResults(testName = "TSH", lowerBound = 0.27, upperBound = 4.20, units = "IU/L", valueType = "float", precision = 2)
normal_total_t3 = NormalTestResults(testName = "Total_T3", lowerBound = 80, upperBound = 200, units = "ng/dL", valueType = "integer")
normal_free_t3 = NormalTestResults(testName = "Free_T3", lowerBound = 2.0, upperBound = 4.4, units = "pg/mL", valueType = "float", precision = 1)
normal_total_t4 = NormalTestResults(testName = "Total_T4", lowerBound = 5.1, upperBound = 14.1, units = "\u03BCg/dL", valueType = "float", precision = 1)
normal_free_t4 = NormalTestResults(testName = "Free_T4", lowerBound = 0.8, upperBound = 1.6, units = "ng/dL", valueType = "float", precision = 1)
normal_vitamin_d_25_oh = NormalTestResults(testName = "Vitamin_D_25_OH", lowerBound = 20, upperBound = 70, units = "ng/mL", valueType = "integer")
normal_vitamin_b_12 = NormalTestResults(testName = "Vitamin_B12", lowerBound = 211, upperBound = 946, units = "pg/mL", valueType = "integer")
normal_folate = NormalTestResults(testName = "Folate", lowerBound = 7.3, upperBound = 26.1, units = "ng/mL", valueType = "float", precision = 1)
normal_osmolality = NormalTestResults(testName = "Osmolality", lowerBound = 285, upperBound = 305, units = "mOsm/kg", valueType = "integer")
normal_total_testosterone = NormalTestResults(testName = "Total_Testosterone", lowerBound = 249, upperBound = 836, units = "ng/dL", valueType = "integer")
normal_p_amylase = NormalTestResults(testName = "p_Amylase", lowerBound = 13, upperBound = 53, units = "IU/L", valueType = "integer")
normal_lipase = NormalTestResults(testName = "Lipase", lowerBound = 13, upperBound = 60, units = "IU/L", valueType = "integer")
normal_ammonia = NormalTestResults(testName = "Ammonia", lowerBound = 16, upperBound = 60, units = "\u03BCmol/L", valueType = "integer")
normal_uric_acid = NormalTestResults(testName = "Uric_Acid", lowerBound = 3.4, upperBound = 7.0, units = "mg/dL", valueType = "float", precision = 1)
normal_total_ck = NormalTestResults(testName = "Total_Creatine_Kinase", lowerBound = 39, upperBound = 192, units = "U/L", valueType = "integer")
normal_troponin_i = NormalTestResults(testName = "Troponin_I", lowerBound = 0.00, upperBound = 0.03, units = "\u03BCg/L", valueType = "float", precision = 2)
normal_acth = NormalTestResults(testName = "ACTH", lowerBound = 7.2, upperBound = 63.3, units = "pg/mL", valueType = "float", precision = 1)
normal_pro_bnp = NormalTestResults(testName = "Pro_BNP", lowerBound = 0, upperBound = 450, units = "pg/mL", valueType = "integer")
normal_beta_hcg = NormalTestResults(testName = "beta_HCG", lowerBound = 0, upperBound = 2.6, units = "mIU/mL", valueType = "float", precision = 1)
normal_urine_sodium = NormalTestResults(testName = "Urine_Sodium", lowerBound = 10, upperBound = 20, units = "mEq/L", valueType = "integer")
normal_urine_total_protein = NormalTestResults(testName = "Urine_Total_Protein", lowerBound = 0, upperBound = 11, units = "mg/dL", valueType = "integer")
normal_urine_creatinine = NormalTestResults(testName = "Urine_Creatinine", lowerBound = 30, upperBound = 125, units = "mg/dL", valueType = "integer")
normal_urine_osmolality = NormalTestResults(testName = "Urine_Osmolality", lowerBound = 285, upperBound = 305, units = "mOsm/kg", valueType = "integer")
normal_microalbumin = NormalTestResults(testName = "Microalbumin", lowerBound = 0, upperBound = 19, units = "mg/dL", valueType = "integer")
normal_cortisol_am = NormalTestResults(testName = "Cortisol_AM", lowerBound = 6.0, upperBound = 18.4, units = "\u03BCg/dL", valueType = "float", precision = 1)
normal_salicylate = NormalTestResults(testName = "Salicylate", lowerBound = 10, upperBound = 30, units = "mg/dL", valueType = "integer")
normal_acetaminophen = NormalTestResults(testName = "Acetaminophen", lowerBound = 10, upperBound = 20, units = "\u03BCg/mL", valueType = "integer")
normal_c_peptide = NormalTestResults(testName = "C_Peptide", lowerBound = 1.1, upperBound = 4.4, units = "ng/mL", valueType = "float", precision = 1)
normal_c3 = NormalTestResults(testName = "C3", lowerBound = 90, upperBound = 180, units = "mg/dL", valueType = "integer")
normal_c4 = NormalTestResults(testName = "C4", lowerBound = 10, upperBound = 40, units = "mg/dL", valueType = "integer")
normal_ggt = NormalTestResults(testName = "GGT", lowerBound = 10, upperBound = 71, units = "U/L", valueType = "integer")
normal_iga = NormalTestResults(testName = "IgA", lowerBound = 70, upperBound = 400, units = "mg/dL", valueType = "integer")
normal_igg = NormalTestResults(testName = "IgG", lowerBound = 700, upperBound = 1600, units = "mg/dL", valueType = "integer")
normal_igm = NormalTestResults(testName = "IgM", lowerBound = 40, upperBound = 230, units = "mg/dL", valueType = "integer")
normal_insulin = NormalTestResults(testName = "Insulin", lowerBound = 3, upperBound = 19, units = "\u03BCU/mL", valueType = "integer")
normal_prealbumin = NormalTestResults(testName = "Prealbumin", lowerBound = 20.0, upperBound = 40.0, units = "mg/dL", valueType = "float", precision = 1)
normal_prolactin = NormalTestResults(testName = "Prolactin", lowerBound = 4.04, upperBound = 15.2, units = "ng/dL", valueType = "float", precision = 2)
normal_pth_intact = NormalTestResults(testName = "PTH_intact", lowerBound = 16, upperBound = 65, units = "pg/mL", valueType = "integer")
normal_rf = NormalTestResults(testName = "Rheumatoid_Factor", lowerBound = 0, upperBound = 14, units = "U/mL", valueType = "integer")
normal_total_psa = NormalTestResults(testName = "Total_PSA", lowerBound = 0.0, upperBound = 4.0, units = "ng/mL", valueType = "float", precision = 1)
normal_bohb = NormalTestResults(testName = "beta_Hydroxybutyrate", lowerBound = 0.02, upperBound = 0.27, units = "mmol/L", valueType = "float", precision = 2)
normal_pt_inr = NormalTestResults(testName = "PT_INR", lowerBound = 0.8, upperBound = 1.2, units = "", valueType = "float", precision = 1)
normal_aptt = NormalTestResults(testName = "APTT", lowerBound = 25.0, upperBound = 37.0, units = "seconds", valueType = "float", precision = 1)
normal_fibrinogen = NormalTestResults(testName = "Fibrinogen", lowerBound = 200, upperBound = 400, units = "mg/dL", valueType = "integer")
normal_hemoglobin = NormalTestResults(testName = "Hemoglobin", lowerBound = 13.1, upperBound = 17.5, units = "g/dL", valueType = "float", precision = 1)
normal_platelet_count = NormalTestResults(testName = "Platelet_Count", lowerBound = 150, upperBound = 400, units = "10\u00b3/\u03BCL", valueType = "integer")
normal_wbc_count = NormalTestResults(testName = "WBC_Count", lowerBound = 4.0, upperBound = 10.0, units = "10\u00b3/dL", valueType = "float", precision = 1)
add(normal_acetaminophen)
add(normal_acth)
add(normal_albumin)
add(normal_alk_phos)
add(normal_alt)
add(normal_ammonia)
add(normal_aptt)
add(normal_ast)
add(normal_beta_hcg)
add(normal_bohb)
add(normal_bun)
add(normal_c3)
add(normal_c4)
add(normal_c_peptide)
add(normal_calcium)
add(normal_chloride)
add(normal_co2)
add(normal_cortisol_am)
add(normal_creatinine)
add(normal_crp)
add(normal_direct_bilirubin)
add(normal_ferritin)
add(normal_fibrinogen)
add(normal_folate)
add(normal_free_t3)
add(normal_free_t4)
add(normal_ggt)
add(normal_glucose)
add(normal_hdl)
add(normal_hemoglobin)
add(normal_iga)
add(normal_igg)
add(normal_igm)
add(normal_insulin)
add(normal_iron)
add(normal_ldl)
add(normal_lipase)
add(normal_mg)
add(normal_microalbumin)
add(normal_osmolality)
add(normal_p_amylase)
add(normal_phosphorus)
add(normal_platelet_count)
add(normal_potassium)
add(normal_prealbumin)
add(normal_pro_bnp)
add(normal_prolactin)
add(normal_pt_inr)
add(normal_pth_intact)
add(normal_rf)
add(normal_salicylate)
add(normal_sodium)
add(normal_total_bilirubin)
add(normal_total_cholesterol)
add(normal_total_ck)
add(normal_total_protein)
add(normal_total_psa)
add(normal_total_t3)
add(normal_total_t4)
add(normal_total_testosterone)
add(normal_transferrin)
add(normal_triglycerides)
add(normal_troponin_i)
add(normal_tsh)
add(normal_uric_acid)
add(normal_urine_creatinine)
add(normal_urine_osmolality)
add(normal_urine_sodium)
add(normal_urine_total_protein)
add(normal_vitamin_b_12)
add(normal_vitamin_d_25_oh)
add(normal_wbc_count)